spring:
    datasource:
        maximum-pool-size: 10
        driver-class-name: com.mysql.jdbc.Driver
        auto-commit: true
        connection-test-query: SELECT 1
        connectionTimeout: 20000
        maxLifetime: 60000
    mvc:
      favicon:
        enabled: false
    output:
      ansi:
        enabled: always
    aop:
      proxy-target-class: true
mybatis:
  mapper-locations: mapper/*.xml